"""create_invoices_and_line_items

Revision ID: c331eb890248
Revises: 
Create Date: 2026-07-23 14:35:29.901542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c331eb890248'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('document_label', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('po_number', sa.String(length=128), nullable=True),
    sa.Column('vendor_name', sa.String(length=512), nullable=True),
    sa.Column('vendor_gstin', sa.String(length=32), nullable=True),
    sa.Column('buyer_name', sa.String(length=512), nullable=True),
    sa.Column('buyer_gstin', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file', name='uq_invoices_source_file')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_message_id'), 'invoices', ['message_id'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index(op.f('ix_invoices_message_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
